.TH ocsptool "1" "January 2012"
.SH NAME
ocsptool \- commandline OCSP application
.SH DESCRIPTION
This is a program that can parse and print information about OCSP
requests/responses, generate requests and verify responses. 
.SH OPTIONS
\fB\-e\fR, \fB\-\-verify\-response\fR
Verify response.
.TP
\fB\-i\fR, \fB\-\-request\-info\fR
Print information on a OCSP request.
.TP
\fB\-j\fR, \fB\-\-response\-info\fR
Print information on a OCSP response.
.TP
\fB\-q\fR, \fB\-\-generate\-request\fR
Generate a OCSP request.
.TP
\fB\-\-no\-nonce\fR
don't add nonce to OCSP request.
.TP
\fB\-\-load\-issuer\fR FILE
read issuer certificate from FILE.
.TP
\fB\-\-load\-cert\fR FILE
read certificate to check from FILE.
.TP
\fB\-\-load\-trust\fR FILE
read OCSP trust anchors from FILE.
.TP
\fB\-\-load\-signer\fR FILE
read OCSP response signer from FILE.
.TP
\fB\-\-inder\fR
Use DER format for input certificates.
.TP
\fB\-Q\fR, \fB\-\-load\-request\fR FILE
read DER encoded OCSP request from
FILE.
.TP
\fB\-S\fR, \fB\-\-load\-response\fR FILE
read DER encoded OCSP response from
FILE.
.TP
\fB\-\-outfile\fR FILE
Output file.
.TP
\fB\-\-infile\fR FILE
Input file.
.TP
\fB\-V\fR, \fB\-\-verbose\fR
More verbose output.
.TP
\fB\-d\fR, \fB\-\-debug\fR integer
Enable debugging
.TP
\fB\-v\fR, \fB\-\-version\fR
prints the program's version number
.TP
\fB\-h\fR, \fB\-\-help\fR
shows this help text
.SH AUTHOR
ocsptool was written by Simon Josefsson.
.SH "SEE ALSO"
The full documentation for
.B ocsptool
is maintained as a Texinfo manual.  If the
.B info
and
.B ocsptool
programs are properly installed at your site, the command
.IP
.B info gnutls
.PP
should give you access to the complete manual.
